spring.application.name=order-management-backend

spring.mvc.servlet.path=/oms

spring.datasource.url=jdbc:postgresql://localhost:5432/om-db
spring.datasource.username=thet
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

app.jwt.issuer=mpss-oms
app.jwt.secretKey=CLx/iMg2X8zVNmTWVfN8YZfexKu0iPExiBE76fnUdUA+ymQft6GDUnNuTEcZxQnLXVRM71CiN69YqwwIS/blBQ==

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE